const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Timeline,
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.Sin,
		C3.Plugins.TextBox,
		C3.Behaviors.NoSave,
		C3.Plugins.NinePatch,
		C3.Behaviors.Pin,
		C3.Plugins.Dictionary,
		C3.Plugins.Json,
		C3.Plugins.Arr,
		C3.Plugins.Particles,
		C3.Behaviors.Fade,
		C3.Plugins.sliderbar,
		C3.Plugins.Tilemap,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Browser.Acts.LoadStyleSheet,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.OnLoadFailed,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.ScriptsInEvents.Es_maingame_Event14_Act7,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Tilemap.Cnds.CompareInstanceVar,
		C3.Plugins.Tilemap.Acts.SetVisible,
		C3.Plugins.Tilemap.Acts.SetBoolInstanceVar,
		C3.Plugins.Tilemap.Acts.SetOpacity,
		C3.Plugins.Tilemap.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.float,
		C3.Plugins.Touch.Cnds.OnDoubleTapGesture,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Tilemap.Cnds.IsVisible,
		C3.ScriptsInEvents.Es_time_Event1_Act1,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Text.Acts.SetText,
		C3.ScriptsInEvents.Es_time_Event3_Act4,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.ScriptsInEvents.Es_time_Event9_Act1,
		C3.ScriptsInEvents.Es_time_Event10_Act1,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Text.Cnds.CompareWidth,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Plugins.Text.Exps.FaceSize,
		C3.ScriptsInEvents.Es_economics_Event13_Act1,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.Alert,
		C3.ScriptsInEvents.Es_debug_Event3_Act1,
		C3.Plugins.Timeline.Acts.StopAllTimelines,
		C3.Plugins.Text.Acts.SetHeight,
		C3.Plugins.Text.Exps.TextHeight,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Tilemap.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.NinePatch.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetSize,
		C3.ScriptsInEvents.Es_ingameui_Event33_Act3,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.replace,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.CompareTouchSpeed,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.sliderbar.Acts.SetMaximum,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.NinePatch.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba,
		C3.ScriptsInEvents.Es_ingameui_Event123_Act2,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.NinePatch.Acts.SetHeight,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetEffectParam,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Timeline.Cnds.OnKeyframeReached,
		C3.Plugins.Timeline.Acts.PauseTimelineByTags,
		C3.Plugins.Timeline.Exps.KeyframeTags,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Timeline.Acts.ResumeTimelineByTags,
		C3.Plugins.Timeline.Acts.StopTimelineByTags,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Cnds.IsTagPlaying
	];
};
self.C3_JsPropNameTable = [
	{OT_Keyboard: 0},
	{OT_LocalStorage: 0},
	{OT_Touch: 0},
	{OT_AJAX: 0},
	{OT_Browser: 0},
	{OT_Audio: 0},
	{OT_Mouse: 0},
	{OT_TimelineController: 0},
	{Anchor: 0},
	{S_UI_Shop: 0},
	{S_UI_Speed_Fast: 0},
	{S_UI_Speed_Normal: 0},
	{S_UI_Speed_Pause: 0},
	{S_UI_Speed_Selector: 0},
	{T_Money: 0},
	{T_Popularity: 0},
	{T_Timer: 0},
	{description: 0},
	{name: 0},
	{type: 0},
	{build_finished_time: 0},
	{is_available: 0},
	{rent: 0},
	{capacity: 0},
	{initial_frame: 0},
	{S_Building: 0},
	{TB_Borders: 0},
	{TouchStartX: 0},
	{TouchStartY: 0},
	{ScrollTo: 0},
	{"8Direction": 0},
	{S_Camera: 0},
	{TB_Cells: 0},
	{Sine: 0},
	{TB_Water: 0},
	{TI_Log: 0},
	{T_Shop_BuildingName: 0},
	{T_Shop_BuildingDescription: 0},
	{T_Shop_BuildingUtilities: 0},
	{S_Shop_Exit: 0},
	{NoSave: 0},
	{S_Shop_Building: 0},
	{T_Shop_BuildingTileName: 0},
	{T_Shop_BuildingCost: 0},
	{T_Shop_BuyBuilding: 0},
	{T_Shop_Categories: 0},
	{category: 0},
	{S_Shop_Category: 0},
	{S_Shop_CategorySelector: 0},
	{T_Shop_BuildAvailability: 0},
	{NP_Shop_Selector: 0},
	{Pin: 0},
	{S_Building_Target: 0},
	{T_Building_Cost: 0},
	{T_Building_Cancel: 0},
	{T_Building_Name: 0},
	{S_Building_Target_Color: 0},
	{"9P_Building_Border_Green": 0},
	{"9P_Building_Border_Red": 0},
	{event_name: 0},
	{S_Event_Theme: 0},
	{T_Event_TileName: 0},
	{S_Event_ThemeSelector: 0},
	{S_Event_Exit: 0},
	{T_Event_StaticHeaders: 0},
	{T_Event_PeopleMin: 0},
	{T_Event_PeopleMax: 0},
	{T_Event_PeopleCurrent: 0},
	{T_Event_Next: 0},
	{T_Info_BuildingName: 0},
	{T_Info_BuildingDescription: 0},
	{T_Info_BuildingUtilities: 0},
	{T_Info_UpgradeCost: 0},
	{S_Info_Exit: 0},
	{T_Info_UpgradeAvalability: 0},
	{TB_Info_UpgradeLight: 0},
	{T_Info_RemoveAvalability: 0},
	{T_Info_RemoveCost: 0},
	{S_Info_UpgradeLight: 0},
	{T_Notify_Header: 0},
	{T_Notify_Text: 0},
	{option_number: 0},
	{execute_function: 0},
	{T_Notify_Option: 0},
	{S_Notify_Option_Selecter: 0},
	{S_JSON_ok: 0},
	{S_UI_Json: 0},
	{TI_JSON_input: 0},
	{S_Educ_Selector: 0},
	{T_Menu_Header: 0},
	{T_Menu_Continue: 0},
	{T_Menu_NewGame: 0},
	{T_Menu_Settings: 0},
	{T_Menu_SettinsStatic: 0},
	{S_Menu_SoundEnabled: 0},
	{S_Menu_MusicEnabled: 0},
	{S_Menu_Exit: 0},
	{"9patch": 0},
	{"9P_WarningZone": 0},
	{"9P_BuildingZone": 0},
	{D_Buildings: 0},
	{D_Events: 0},
	{J_Buildings: 0},
	{J_Achivements: 0},
	{A_ShopPage: 0},
	{A_EventThemes: 0},
	{A_EventPage: 0},
	{A_Notifications: 0},
	{J_NotifyOptions: 0},
	{J_RandomEvents: 0},
	{A_KustAvailableNodes: 0},
	{S_RE_FirstTile: 0},
	{S_RE_LastTile: 0},
	{S_RE_Cecker: 0},
	{S_Weather_Leave: 0},
	{P_Weather_Leaves: 0},
	{S_Weather_Snow: 0},
	{P_Weather_Snow: 0},
	{Fade: 0},
	{S_Landscape: 0},
	{TB_Grass: 0},
	{Sprite: 0},
	{S_Debug_RestartGame: 0},
	{TB_BuildBlocker: 0},
	{TextInput: 0},
	{SliderBar: 0},
	{TiledBackground: 0},
	{S_World_CloseBuildingChecker: 0},
	{S_Ststic_RequestFullscreen: 0},
	{S_UI_Icon: 0},
	{S_Common_Calendar: 0},
	{Sprite2: 0},
	{S_UI_Season: 0},
	{Line: 0},
	{T_Educ_Text: 0},
	{S_Educ_Ok: 0},
	{FadeIn: 0},
	{FadeOut: 0},
	{TB_Fader: 0},
	{Sprite3: 0},
	{fixed_x: 0},
	{fixed_y: 0},
	{is_active: 0},
	{building_uid: 0},
	{TM_Layer_zabor_0: 0},
	{TM_Layer_zabor_1: 0},
	{TiledBackground2: 0},
	{TB_CellBorders: 0},
	{TM_Layer_zabor_2: 0},
	{TM_Layer_zabor_3: 0},
	{Sprite4: 0},
	{FT_Normal_Text: 0},
	{FTB_BuildBlockers: 0},
	{FS_Building: 0},
	{FTM_Layers: 0},
	{RequireLoading: 0},
	{Initiated: 0},
	{SNAP_CELL_WIDTH: 0},
	{building_camera_fixed: 0},
	{InitiatedSteps: 0},
	{StepsToInitiate: 0},
	{TimelineLoaded: 0},
	{building: 0},
	{field: 0},
	{steps_await: 0},
	{initialDistance: 0},
	{currentDistance: 0},
	{initialScale: 0},
	{scaleFactor: 0},
	{cost: 0},
	{building_type: 0},
	{building_x: 0},
	{building_y: 0},
	{building_upgrade_type: 0},
	{upgrade_width: 0},
	{upgrade_height: 0},
	{total_rent: 0},
	{people: 0},
	{buff: 0},
	{upgrade_modifier: 0},
	{next_tier_cost: 0},
	{next_tier_type: 0},
	{remove_modifier: 0},
	{max_debuff: 0},
	{wall_exists: 0},
	{CurrentTime: 0},
	{TimePerSecond: 0},
	{InitialYear: 0},
	{GameFinished: 0},
	{SPEED_FAST: 0},
	{SPEED_NORMAL: 0},
	{SPEED_PAUSE: 0},
	{TARGETS_TO_LOAD: 0},
	{current_time: 0},
	{function_name: 0},
	{params: 0},
	{event_time: 0},
	{text: 0},
	{Money: 0},
	{StaticSeasonModifier: 0},
	{Popularity: 0},
	{START_MONEY: 0},
	{START_POPULARITY: 0},
	{MAX_DOTATION: 0},
	{new_value: 0},
	{count: 0},
	{dotation: 0},
	{return: 0},
	{money_: 0},
	{UI_Type: 0},
	{Shop_CurrentBuilding: 0},
	{Info_CurrentBuildingUID: 0},
	{Info_UpgradeBlocked: 0},
	{UI_COMMON: 0},
	{UI_JSON: 0},
	{UI_BUILDING: 0},
	{UI_SHOP: 0},
	{UI_INFO: 0},
	{UI_EVENT_1: 0},
	{UI_NOTIFICATION: 0},
	{UI_DISABLED: 0},
	{layer: 0},
	{grid: 0},
	{value: 0},
	{TILES_IN_ROW: 0},
	{create_x: 0},
	{create_y: 0},
	{width: 0},
	{height: 0},
	{init_x: 0},
	{init_y: 0},
	{сategory: 0},
	{resolved_string: 0},
	{string: 0},
	{can_build: 0},
	{TILES_OFFSET_TOP: 0},
	{UI_INFO_9P_UID: 0},
	{upgrade_uid: 0},
	{EXISTS: 0},
	{NOT_EXISTS: 0},
	{required_type: 0},
	{result: 0},
	{NOTIFICATION_HEADER: 0},
	{NOTIFICATION_TEXT: 0},
	{NOTIFICATION_OPTIONS: 0},
	{"9P_UID": 0},
	{function_to_call: 0},
	{header: 0},
	{options_json: 0},
	{current_option_y: 0},
	{resolved_text: 0},
	{id: 0},
	{building_count: 0},
	{first_living_date: 0},
	{"103_hostel_uid": 0},
	{"104_last_check": 0},
	{DAYS_TO_KUST: 0},
	{random_node: 0},
	{"104_days_to_recheck": 0},
	{EducationEnabled: 0},
	{CurrentKF: 0},
	{TRUE: 0},
	{FALSE: 0},
	{SETTINGS_SOUNDS_ENABLED: 0},
	{SETTINGS_MUSIC_ENABLED: 0}
];

self.InstanceType = {
	OT_Keyboard: class extends self.IInstance {},
	OT_LocalStorage: class extends self.IInstance {},
	OT_Touch: class extends self.IInstance {},
	OT_AJAX: class extends self.IInstance {},
	OT_Browser: class extends self.IInstance {},
	OT_Audio: class extends self.IInstance {},
	OT_Mouse: class extends self.IInstance {},
	OT_TimelineController: class extends self.IInstance {},
	S_UI_Shop: class extends self.ISpriteInstance {},
	S_UI_Speed_Fast: class extends self.ISpriteInstance {},
	S_UI_Speed_Normal: class extends self.ISpriteInstance {},
	S_UI_Speed_Pause: class extends self.ISpriteInstance {},
	S_UI_Speed_Selector: class extends self.ISpriteInstance {},
	T_Money: class extends self.ITextInstance {},
	T_Popularity: class extends self.ITextInstance {},
	T_Timer: class extends self.ITextInstance {},
	S_Building: class extends self.ISpriteInstance {},
	TB_Borders: class extends self.ITiledBackgroundInstance {},
	S_Camera: class extends self.ISpriteInstance {},
	TB_Cells: class extends self.ITiledBackgroundInstance {},
	TB_Water: class extends self.ITiledBackgroundInstance {},
	TI_Log: class extends self.ITextInputInstance {},
	T_Shop_BuildingName: class extends self.ITextInstance {},
	T_Shop_BuildingDescription: class extends self.ITextInstance {},
	T_Shop_BuildingUtilities: class extends self.ITextInstance {},
	S_Shop_Exit: class extends self.ISpriteInstance {},
	S_Shop_Building: class extends self.ISpriteInstance {},
	T_Shop_BuildingTileName: class extends self.ITextInstance {},
	T_Shop_BuildingCost: class extends self.ITextInstance {},
	T_Shop_BuyBuilding: class extends self.ITextInstance {},
	T_Shop_Categories: class extends self.ITextInstance {},
	S_Shop_Category: class extends self.ISpriteInstance {},
	S_Shop_CategorySelector: class extends self.ISpriteInstance {},
	T_Shop_BuildAvailability: class extends self.ITextInstance {},
	NP_Shop_Selector: class extends self.IWorldInstance {},
	S_Building_Target: class extends self.ISpriteInstance {},
	T_Building_Cost: class extends self.ITextInstance {},
	T_Building_Cancel: class extends self.ITextInstance {},
	T_Building_Name: class extends self.ITextInstance {},
	S_Building_Target_Color: class extends self.ISpriteInstance {},
	_9P_Building_Border_Green: class extends self.IWorldInstance {},
	_9P_Building_Border_Red: class extends self.IWorldInstance {},
	S_Event_Theme: class extends self.ISpriteInstance {},
	T_Event_TileName: class extends self.ITextInstance {},
	S_Event_ThemeSelector: class extends self.ISpriteInstance {},
	S_Event_Exit: class extends self.ISpriteInstance {},
	T_Event_StaticHeaders: class extends self.ITextInstance {},
	T_Event_PeopleMin: class extends self.ITextInstance {},
	T_Event_PeopleMax: class extends self.ITextInstance {},
	T_Event_PeopleCurrent: class extends self.ITextInstance {},
	T_Event_Next: class extends self.ITextInstance {},
	T_Info_BuildingName: class extends self.ITextInstance {},
	T_Info_BuildingDescription: class extends self.ITextInstance {},
	T_Info_BuildingUtilities: class extends self.ITextInstance {},
	T_Info_UpgradeCost: class extends self.ITextInstance {},
	S_Info_Exit: class extends self.ISpriteInstance {},
	T_Info_UpgradeAvalability: class extends self.ITextInstance {},
	TB_Info_UpgradeLight: class extends self.ITiledBackgroundInstance {},
	T_Info_RemoveAvalability: class extends self.ITextInstance {},
	T_Info_RemoveCost: class extends self.ITextInstance {},
	S_Info_UpgradeLight: class extends self.ISpriteInstance {},
	T_Notify_Header: class extends self.ITextInstance {},
	T_Notify_Text: class extends self.ITextInstance {},
	T_Notify_Option: class extends self.ITextInstance {},
	S_Notify_Option_Selecter: class extends self.ISpriteInstance {},
	S_JSON_ok: class extends self.ISpriteInstance {},
	S_UI_Json: class extends self.ISpriteInstance {},
	TI_JSON_input: class extends self.ITextInputInstance {},
	S_Educ_Selector: class extends self.ISpriteInstance {},
	T_Menu_Header: class extends self.ITextInstance {},
	T_Menu_Continue: class extends self.ITextInstance {},
	T_Menu_NewGame: class extends self.ITextInstance {},
	T_Menu_Settings: class extends self.ITextInstance {},
	T_Menu_SettinsStatic: class extends self.ITextInstance {},
	S_Menu_SoundEnabled: class extends self.ISpriteInstance {},
	S_Menu_MusicEnabled: class extends self.ISpriteInstance {},
	S_Menu_Exit: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	_9P_WarningZone: class extends self.IWorldInstance {},
	_9P_BuildingZone: class extends self.IWorldInstance {},
	D_Buildings: class extends self.IDictionaryInstance {},
	D_Events: class extends self.IDictionaryInstance {},
	J_Buildings: class extends self.IJSONInstance {},
	J_Achivements: class extends self.IJSONInstance {},
	A_ShopPage: class extends self.IArrayInstance {},
	A_EventThemes: class extends self.IArrayInstance {},
	A_EventPage: class extends self.IArrayInstance {},
	A_Notifications: class extends self.IArrayInstance {},
	J_NotifyOptions: class extends self.IJSONInstance {},
	J_RandomEvents: class extends self.IJSONInstance {},
	A_KustAvailableNodes: class extends self.IArrayInstance {},
	S_RE_FirstTile: class extends self.ISpriteInstance {},
	S_RE_LastTile: class extends self.ISpriteInstance {},
	S_RE_Cecker: class extends self.ISpriteInstance {},
	S_Weather_Leave: class extends self.ISpriteInstance {},
	P_Weather_Leaves: class extends self.IParticlesInstance {},
	S_Weather_Snow: class extends self.ISpriteInstance {},
	P_Weather_Snow: class extends self.IParticlesInstance {},
	S_Landscape: class extends self.ISpriteInstance {},
	TB_Grass: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	S_Debug_RestartGame: class extends self.ISpriteInstance {},
	TB_BuildBlocker: class extends self.ITiledBackgroundInstance {},
	TextInput: class extends self.ITextInputInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	S_World_CloseBuildingChecker: class extends self.ISpriteInstance {},
	S_Ststic_RequestFullscreen: class extends self.ISpriteInstance {},
	S_UI_Icon: class extends self.ISpriteInstance {},
	S_Common_Calendar: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	S_UI_Season: class extends self.ISpriteInstance {},
	Line: class extends self.ITiledBackgroundInstance {},
	T_Educ_Text: class extends self.ITextInstance {},
	S_Educ_Ok: class extends self.ISpriteInstance {},
	TB_Fader: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TM_Layer_zabor_0: class extends self.ITilemapInstance {},
	TM_Layer_zabor_1: class extends self.ITilemapInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TB_CellBorders: class extends self.ITiledBackgroundInstance {},
	TM_Layer_zabor_2: class extends self.ITilemapInstance {},
	TM_Layer_zabor_3: class extends self.ITilemapInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	FT_Normal_Text: class extends self.ITextInstance {},
	FTB_BuildBlockers: class extends self.ITiledBackgroundInstance {},
	FS_Building: class extends self.ISpriteInstance {},
	FTM_Layers: class extends self.ITilemapInstance {}
}